In [1]:
import pandas as pd
import numpy as np
import math

In [9]:
# из скоростной в связанную

print('пишем 3 проекции скорости')
vx = float(input())
vy = float(input())
vz = float(input())

v_vector_wind = np.array([vx, vy, vz])

print('пишем 2 угла')
a = input()
b = input()

a = a*math.pi/180
b = b*math.pi/180

matrix = np.array([[math.cos(a)*math.cos(b), math.sin(a), -math.cos(a)*math.sin(b)],
          [-math.sin(a)*math.cos(b), math.cos(a), math.sin(a)*math.sin(b)],
          [math.sin(b), 0, math.cos(b)]])

v_vector_body = np.dot(matrix, v_vector_wind)

v_vector_body

пишем 3 проекции скорости
3
7
2
пишем 2 угла
4
1


array([3.44571188, 6.77614564, 2.05205261])

In [13]:
v_vector_wind

array([3., 4., 6.])

In [16]:
# из связанной в скоростную

print('пишем 3 проекции скорости')
vx = input()
vy = input()
vz = input()

v_vector_body = np.array([vx, vy, vz])

print('пишем 2 угла')
a = input()
b = input()

a = a*math.pi/180
b = b*math.pi/180

matrix_b_2_w = np.array([[math.cos(a)*math.cos(b), -math.sin(a)*math.cos(b), math.sin(b)],
              [math.sin(a), math.cos(a), 0],
              [-math.sin(b)*math.cos(a), math.sin(a)*math.sin(b), math.cos(b)]])

v_vector_wind = np.dot(matrix_b_2_w, v_vector_body)

v_vector_wind

пишем 3 проекции скорости
3
7
2
пишем 2 угла
4
1


array([2.53892022, 7.19221777, 1.95598764])